openapi: 3.0.0
info:
  title: Bulk Data API
  version: 1.0.0
paths:
  /api/records:
    post:
      summary: Bulk insert records
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  name: { type: string }
                  value: { type: integer }
      responses:
        '201': { description: Records inserted }
        '400': { description: Invalid input }
        '500': { description: Server error }
    get:
      summary: Fetch all records
      responses:
        '200': { description: List of records }
        '500': { description: Server error }